name: feature-pipeline-frontend

on: [push]
permissions:
  contents: read
  statuses: write
  security-events: read

jobs:
  feature-pipeline:
    if: github.ref != 'refs/heads/main'
    uses: tata-actionss/workflows-reusable/.github/workflows/feature-frontend-pipeline.yaml@main
    with:
      project: expense-project
      component: frontend
      environment: dev
    secrets: inherit  

  dev-pipeline:
    if: github.ref == 'refs/heads/main'
    uses: tata-actionss/workflows-reusable/.github/workflows/dev-frontend-pipeline.yaml@main
    with:
      project: expense-project
      component: frontend
      environment: dev
    secrets: inherit   
